# Generated by Django 4.2 on 2023-04-15 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='brigada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brigada', to='garbage.brigada'),
        ),
        migrations.AddField(
            model_name='task',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
    ]
