# Generated by Django 4.1.4 on 2023-04-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garbage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
