# Generated by Django 4.2 on 2023-04-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0002_task_brigada_task_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='brigada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='client',
            field=models.TextField(blank=True, null=True),
        ),
    ]
